experiment:
  name: XRAY-64x64-AUGMENTED-HALF-HALF-v2
  version: 0.0.0
  use_cuda: true
  
  model:
    epochs: 20000
    max_epochs_without_improvement: 10000
    learning_rate: 0.001
    train_batch_size: 256
    test_batch_size: 256
    input_dropout: 0.2
    dense_dropout: 0

  dataset:
    name: XRAY
    image_resolution: 64
    normalization_mean: 0
    normalization_std: 1