experiments:

  # - name: XRAY-64x64-SYNTHETIC-BALANCED
  #   use_cuda: true
    
  #   model:
  #     epochs: 5000
  #     max_epochs_without_improvement: 800
  #     learning_rate: 0.001
  #     train_batch_size: 256
  #     val_batch_size: 8
  #     test_batch_size: 256
  #     input_dropout: 0.2
  #     dense_dropout: 0

  #   dataset:
  #     name: XRAY
  #     train_path: data/preprocessed/xray_generated/train
  #     validation_path: data/preprocessed/xray_generated/val
  #     test_path: data/preprocessed/xray_resized/test
  #     image_resolution: 64
  #     normalization_mean: 0
  #     normalization_std: 1
  
  # - name: XRAY-64x64-SYNTHETIC-UNBALANCED
  #   use_cuda: true
    
  #   model:
  #     epochs: 5000
  #     max_epochs_without_improvement: 800
  #     learning_rate: 0.001
  #     train_batch_size: 256
  #     val_batch_size: 8
  #     test_batch_size: 256
  #     input_dropout: 0.2
  #     dense_dropout: 0

  #   dataset:
  #     name: XRAY
  #     train_path: data/preprocessed/xray_generated_unbalanced/train
  #     validation_path: data/preprocessed/xray_generated_unbalanced/val
  #     test_path: data/preprocessed/xray_resized/test
  #     image_resolution: 64
  #     normalization_mean: 0
  #     normalization_std: 1
  
  
  - name: XRAY-64x64-REAL
    use_cuda: true
    
    model:
      epochs: 10000
      max_epochs_without_improvement: 1200
      learning_rate: 0.001
      train_batch_size: 256
      val_batch_size: 8
      test_batch_size: 256
      input_dropout: 0.2
      dense_dropout: 0

    dataset:
      name: XRAY
      train_path: data/preprocessed/xray_resized/train
      validation_path: data/preprocessed/xray_resized/val
      test_path: data/preprocessed/xray_resized/test
      image_resolution: 64
      normalization_mean: 0
      normalization_std: 1
  